MVC/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class EmployeesController : Controller
    {
        private sampleEntityEmployee db = new sampleEntityEmployee();

        // GET: Employees
        public ActionResult Index()
        {
            return View(db.Employees.ToList());
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Gender,City,DateOfBirth")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Gender,City,DateOfBirth")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public JsonResult IsUserNameAvailable(string Name)
        {
            return Json(!db.Employees.Any(x => x.Name == Name),
                                                 JsonRequestBehavior.AllowGet);
        }


    }
}

MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using System.Text;
using MVCDemo.Common;
using Newtonsoft.Json;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            // Store the list of Countries in ViewBag.  
            ViewBag.Countries = new List<string>()
            {
                "India",
                "US",
                "UK",
                "Canada"
            };

            // Store the list of Countries in ViewBag.  
            ViewData["Countries"] = new List<string>()
            {
                "India",
                "US",
                "UK",
                "Canada"
            };

            // Finally return a view

            // Connect to the database
            sampleDBContext db= new sampleDBContext();
            // Retrieve departments, and build SelectList
            ViewBag.departmentsOneoff = new SelectList(db.Departments, "Id", "Name",1);

            // text box for and drop down for stringly typed
            Company company = new Company("Pragim");
            ViewBag.Departments = new SelectList(company.Departments, "Id", "Name");
            ViewBag.CompanyName = company.CompanyName;

            return View(company);
        }

        [HttpGet]
        public ActionResult Index2()
        {
            Company2 company = new Company2();
            return View(company);
        }


        [HttpPost]
        public string Index2(Company2 company)
        {
            if (string.IsNullOrEmpty(company.SelectedDepartment))
            {
                return "You did not select any department";
            }
            else
            {
                return "You selected department with ID = " + company.SelectedDepartment;
            }
        }



        [HttpGet]
        public ActionResult Index3()
        {
            SampleDBConextCheckbox db = new SampleDBConextCheckbox();
            return View(db.Cities);
        }

        [HttpPost]
        public string Index3(IEnumerable<City> cities)
        {
            if (cities.Count(x => x.IsSelected) == 0)
            {
                return "You have not selected any City";
            }
            else
            {
                StringBuilder sb = new StringBuilder();
                sb.Append("You selected - ");
                foreach (City city in cities)
                {
                    if (city.IsSelected)
                    {
                        sb.Append(city.Name + ", ");
                    }
                }
                sb.Remove(sb.ToString().LastIndexOf(","), 1);
                return sb.ToString();
            }
        }


        [HttpGet]
        public ActionResult Index4()
        {
            SampleDBConextCheckbox db = new SampleDBConextCheckbox();
            List<SelectListItem> listSelectListItems = new List<SelectListItem>();

            foreach (City city in db.Cities)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = city.Name,
                    Value = city.ID.ToString(),
                    Selected = city.IsSelected
                };
                listSelectListItems.Add(selectList);
            }

            CitiesViewModel citiesViewModel = new CitiesViewModel()
            {
                Cities = listSelectListItems
            };

            return View(citiesViewModel);
        }

        [HttpPost]
        public string Index4(IEnumerable<string> selectedCities)
        {
            if (selectedCities == null)
            {
                return "No cities selected";
            }
            else
            {
                StringBuilder sb = new StringBuilder();
                sb.Append("You selected - " + string.Join(",", selectedCities));
                return sb.ToString();
            }
        }
        
        [HttpGet]
        public ActionResult Index5(int id)
        {
            sampleEntityEmployee db = new sampleEntityEmployee();
            Employee employee = db.Employees.Single(x => x.Id == id);
            ViewBag.EmployeeData = employee;
            return View(employee);

        }

        [HttpGet]
        public ActionResult Index6()
        {
            sampleEntityEmployee db = new sampleEntityEmployee();
            return View(db.Employees.ToList());
        }

        [HttpGet]
        public ActionResult Index7()
        {
            sampleEntityEmployee db = new sampleEntityEmployee();
            return View(db.Employees.ToList());
        }


        [HttpGet]
        public ActionResult Index8()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Index9()
        {
            return View();
        }


        //Part 67 Action selectors in mvc
        [ActionName("List")]
        [HttpGet]
        public ActionResult Index10()
        {
            return View("Index10");
        }

        [HttpGet]
        [HandleError]
        [RequireHttps]
        [ValidateInput(false)]
        public ActionResult Index11()
        {
            throw new Exception("Something went wrong");
        }

        [TrackExecutionTime]
        public string Index12()
        {
            return "Index Action Invoked";
        }

        [TrackExecutionTime]
        public string Index13()
        {
            throw new Exception("Exception occured");
        }

        public JsonResult Index14()
        {
            return Json("JSON Action type", JsonRequestBehavior.AllowGet);
        }






    }
}

MVC/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Models
{
    public class StudentsController : Controller
    {
        // Create an instance of DatabaseContext class
        sampleDBContextStudents db = new sampleDBContextStudents();

        public ActionResult Index()
        {
            return View();
        }

        // Return all students
        public PartialViewResult All()
        {
            System.Threading.Thread.Sleep(5000);
            List<Student> model = db.Students.ToList();
            return PartialView("_Student", model);
        }

        // Return Top3 students
        public PartialViewResult Top3()
        {
            List<Student> model = db.Students.OrderByDescending(x => x.TotalMarks).Take(3).ToList();
            return PartialView("_Student", model);
        }

        // Return Bottom3 students
        public PartialViewResult Bottom3()
        {
            List<Student> model = db.Students.OrderBy(x => x.TotalMarks).Take(3).ToList();
            return PartialView("_Student", model);
        }



        public ActionResult Index2()
        {
            sampleDBContextStudents db = new sampleDBContextStudents();
            return View(db.Students);
        }

        [HttpPost]
        public ActionResult Index2(string searchTerm)
        {
            sampleDBContextStudents db = new sampleDBContextStudents();
            List<Student> students;
            if (string.IsNullOrEmpty(searchTerm))
            {
                students = db.Students.ToList();
            }
            else
            {
                students = db.Students
                    .Where(s => s.Name.StartsWith(searchTerm)).ToList();
            }
            return View(students);
        }

        public JsonResult GetStudents(string term)
        {
            sampleDBContextStudents db = new sampleDBContextStudents();
            List<string> students = db.Students.Where(s => s.Name.StartsWith(term))
                .Select(x => x.Name).ToList();
            return Json(students, JsonRequestBehavior.AllowGet);
        }






















    }
}

MVC/Views/Home/Index.cshtml
@model MVC.Models.Company

@{
    Layout = null;
    ViewBag.Title = "Index1";
}

<h2>Countries List</h2>

<ul>
    @foreach (string strCountry in ViewBag.Countries)
    {
        <li>@strCountry</li>
    }
</ul>

<br />

<ul>
    @foreach (string strCountry1 in (List<string>)ViewData["Countries"])
    {
        <li>@strCountry1</li>
    }
</ul>

<h3>HTML Helpers</h3>

<h3>Textbox</h3>
@Html.TextBox("firstname", "John", new { style = "background-color:Red; color:White; font-weight:bold", title = "Please enter your first name" })
<br />
<h5>Read only</h5>
@Html.TextBox("firstname", "John", new { @class = "redtextbox", @readonly = "true" })
<br />
<h5>To generate a label for "First Name"</h5>
@Html.Label("fisrtname", "First Name")
<br />
<h5>To generate a textbox to enter password, so that the input is masked</h5>
@Html.Password("Password")
<br />
<h5>To generate a multi-line textbox. 5 lines 20 columns</h5>
@Html.TextArea("Comments", "", 5, 20, null)
<br />
<h5>To generate a hidden textbox</h5>
@Html.Hidden("id")


<h3>Drop Down Lists</h3>
<h5>Hard coded list</h5>
@Html.DropDownList("Departments", new List<SelectListItem>
{
    new SelectListItem { Text = "IT", Value = "1", Selected=true},
    new SelectListItem { Text = "HR", Value = "2"},
    new SelectListItem { Text = "Payroll", Value = "3"}
}, "Select Department") 

<h5>From server</h5>
@*Name from view bag*@
@Html.DropDownList("departmentsOneoff", "Select Department") 


<h3>Text Box vs Text Box For</h3>
Html.TextBox amd Html.DropDownList are not strongly typed
<br />
@Html.TextBoxFor(m => m.CompanyName)
<br />
@Html.DropDownListFor(m => m.Departments, new SelectList(Model.Departments, "Id", "Name"), "Select Department")


<h3>Radio button html helper (Also example of Html ActionLink)</h3>
@Html.ActionLink("Radio Html Helper","Index2", "Home")

<h3>Also example of listing Raw HTML</h3>
@Html.Raw("Next space <br> Some html text <br>")

<h3>Check box html helper</h3>
@Html.ActionLink("Check Box Html Helper", "Index3", "Home")

<h3>List Box box html helper</h3>
@Html.ActionLink("List Box Html Helper", "Index4", "Home")

<h3>Advantages of Stringly typed views</h3>
<h3>With ViewBag and Dynamic type no checking</h3>
@Html.ActionLink("Advantages of Stringly typed views", "Index5", "Home",new { id = "1" }, null)

<h3>Partial view</h3>
@Html.ActionLink("Partial view", "Index6", "Home")

<h3>Render Partial and Partial view differences</h3>
<h5>The return type of "RenderPartial" is void, where as "Partial" returns "MvcHtmlString"</h5>
<h5>Syntax for invoking Partial() and RenderPartial() methods in Razor views</h5>
@Html.ActionLink("Render Partial view", "Index7", "Home")

<h3>Razor view syntax</h3>
@Html.ActionLink("Razor view syntax", "Index8", "Home")

<h3>Layout view in mvc</h3>
<h5>Maintain consistentlook and feel</h5>
@Html.ActionLink("Layout view in mvc", "Index9", "Home")

<h3>Action filters</h3>
@Html.ActionLink("Action filters", "List", "Home")

<h3>HandleError attribute</h3>
<h3>Require HTTPS attribute</h3>
<h3>[ValidateInput(false)] Attribute. Does not allow you to submit any HTML by default to prevent XSS (Cross site scripting attacks)</h3>
@Html.ActionLink("HandleError attribute", "Index11", "Home")

<h3>Custom Action filter</h3>
<h3>Run before or after action method</h3>
@Html.ActionLink("Custom Action filter", "Index12", "Home")
@Html.ActionLink("Trigger Customer Error Action Filter", "Index13", "Home")

<h3>Different Types of Action Results</h3>
@Html.ActionLink("Different Types of Action Results", "Index14", "Home")

<h3>Vailidation (Client and server)</h3>
@Html.ActionLink("Vailidation (Client and server)", "Index", "Employees")

<h3>Ajax Ajax.ActionLink</h3>
@Html.ActionLink("Ajax Ajax.ActionLink", "Index", "Students")

<h3>Ajax Auto Complete</h3>
@Html.ActionLink("Ajax Auto Complete", "Index2", "Students")

MVC/Views/Home/Index10.cshtml
@{
    ViewBag.Title = "Index10";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Index10</h2>

MVC/Views/Home/Index11.cshtml
@{
    ViewBag.Title = "Index11";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Index11</h2>

MVC/Views/Home/Index12.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index12</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MVC/Views/Home/Index15.cshtml
@model MVC.Models.Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index15</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Employee</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

MVC/Views/Home/Index2.cshtml
@model MVC.Models.Company2

@{
    ViewBag.Title = "Index2";
    Layout = null;
}

<h2>Index2</h2>

@using (Html.BeginForm())
{
    foreach (var department in Model.Departments)
    {
        @Html.RadioButtonFor(m => m.SelectedDepartment, department.Id) @department.Name
    }
    <br />
    <br />
    <input type="submit" value="Submit" />
}

MVC/Views/Home/Index3.cshtml
@model IEnumerable<MVC.Models.City>
@{
    ViewBag.Title = "Index";
}
<div style="font-family:Arial">
    <h2>Index</h2>

    @using (Html.BeginForm())
    {
        @Html.EditorForModel()
        <br />
        <input type="submit" value="Submit" />
    }
</div> 

MVC/Views/Home/Index4.cshtml
@model MVC.Models.CitiesViewModel

@{
    Layout = null;
}

<div style="font-family:Arial">
    <h2>Index</h2>
    @using (Html.BeginForm())
    {
        @Html.ListBoxFor(m => m.SelectedCities, Model.Cities, new { size = 4 })
        <br />
        <input type="submit" value="Submit" />
    }
</div>

MVC/Views/Home/Index5.cshtml
@model MVC.Models.Employee

@{
    Layout = null;
}

<div class="display-label">
    @Html.DisplayName("FullName")
</div>
<div class="display-field">
    @Model.Name
</div>
<div class="display-label">
    @Html.DisplayName("Gender")
</div>
<div class="display-field">
    @Model.Gender
</div>

MVC/Views/Home/Index6.cshtml
@model IEnumerable<MVC.Models.Employee>

@{
    Layout = null;
}


@foreach (var item in Model)
{
    @Html.Partial("_Employee", item)
} 

MVC/Views/Home/Index7.cshtml
@model IEnumerable<MVC.Models.Employee>

@{
    Layout = null;
}


@foreach (var item in Model)
{
    { Html.RenderPartial("_Employee", item); }
} 

MVC/Views/Home/Index8.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<h3>Use @@ to switch between c# code and html.</h3>
@for (int i = 1; i <= 10; i++)
{
    <b>@i</b>
}



<h3>Use @@{} to define a code block. If we want to define some variables and perform calculations, then use code block. The following code block defines 2 variables and computes the sum of first 10 even and odd numbers.</h3>
@{
    int SumOfEvenNumbers = 0;
    int SumOfOddNumbers = 0;

    for (int i = 1; i <= 10; i++)
    {
        if (i % 2 == 0)
        {
            SumOfEvenNumbers = SumOfEvenNumbers + i;
        }
        else
        {
            SumOfOddNumbers = SumOfOddNumbers + i;
        }
    }
}

<h3>Sum of Even Numbers = @SumOfEvenNumbers</h3>
<h3>Sum of Odd Numbers = @SumOfOddNumbers</h3>

<h3>Use look at cshtml page</h3>
@for (int i = 1; i <= 10; i++)
{
    <b>@i</b>
    if (i % 2 == 0)
    {
        @: - Even
    }
    else
    {
        @: - Odd
    }
    <br />
}


<h3>Using explicit code nugget</h3>
@for (int i = 1; i <= 5; i++)
{
    <h5>"~/Images/@(i).png"</h5>
}


<h3>Use two @@ symbol to escape @@</h3>
@for (int i = 1; i <= 5; i++)
{
    <h5>"~/Images/@(i).png"</h5>
}

<h3>Transition between c# expressions and literal text</h3>
@{
    int day = 31;
    int month = 12;
    int year = 2013;
}

Date is @day-@month-@year

MVC/Views/Home/Index9.cshtml
@{
    ViewBag.Title = "Index9";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Index9 replace from layout</h2>